export const businessDefinitions = [
  {
    id: "lemon-stand",
    name: "檸檬水攤",
    category: "食品",
    description: "在社區活動旁賣新鮮檸檬水。",
    illustrationKey: "lemon-cup",
    startupCost: 2200,
    purchasePrice: 2200,
    monthlyRevenue: 1800,
    monthlyFixedCost: 300,
    monthlyVariableCost: 520,
    monthlyProfit: 980,
    currentValue: 2600,
    resaleValue: 2200,
    riskLevel: "低",
    growthLevel: 1,
    maxLevel: 3,
    condition: "良好",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 8,
    passiveRatio: 0.15,
    failureRisk: 0.05,
    eventSensitivity: 0.8,
    status: "available",
    childNote: "小攤位容易開始，但需要你花時間準備和銷售。",
    upgradeOptions: [
      { id: "better-stand", name: "改善設備", cost: 900, revenueChange: 420, costChange: 80, valueChange: 700, riskChange: -0.01, passiveChange: 0.03 },
      { id: "event-sign", name: "增加廣告", cost: 700, revenueChange: 360, costChange: 90, valueChange: 500, riskChange: 0, passiveChange: 0.01 },
      { id: "helper", name: "聘請幫手", cost: 1200, revenueChange: 620, costChange: 300, valueChange: 900, riskChange: 0.01, passiveChange: 0.14 },
    ],
  },
  {
    id: "campus-snack",
    name: "校園點心攤",
    category: "食品",
    description: "放學時販售簡單點心和飲料。",
    illustrationKey: "snack-box",
    startupCost: 4200,
    purchasePrice: 4200,
    monthlyRevenue: 3600,
    monthlyFixedCost: 650,
    monthlyVariableCost: 1250,
    monthlyProfit: 1700,
    currentValue: 5200,
    resaleValue: 4400,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "普通",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 14,
    passiveRatio: 0.1,
    failureRisk: 0.08,
    eventSensitivity: 1,
    status: "available",
    childNote: "營收看起來多，但原料成本也會跟著增加。",
    upgradeOptions: [
      { id: "quality-menu", name: "提升產品品質", cost: 1800, revenueChange: 900, costChange: 260, valueChange: 1300, riskChange: -0.01, passiveChange: 0.02 },
      { id: "more-service", name: "增加服務", cost: 1600, revenueChange: 780, costChange: 300, valueChange: 1100, riskChange: 0.01, passiveChange: 0 },
      { id: "part-time", name: "聘請員工", cost: 2600, revenueChange: 1200, costChange: 620, valueChange: 1800, riskChange: 0.01, passiveChange: 0.18 },
    ],
  },
  {
    id: "pet-walk",
    name: "寵物散步服務",
    category: "寵物服務",
    description: "幫鄰居固定遛狗和照顧寵物。",
    illustrationKey: "pet-leash",
    startupCost: 1600,
    purchasePrice: 1600,
    monthlyRevenue: 3000,
    monthlyFixedCost: 260,
    monthlyVariableCost: 420,
    monthlyProfit: 2320,
    currentValue: 2600,
    resaleValue: 1700,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "良好",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 22,
    passiveRatio: 0.05,
    failureRisk: 0.07,
    eventSensitivity: 1,
    status: "available",
    childNote: "收入不錯，但多數收入需要你親自投入時間。",
    upgradeOptions: [
      { id: "booking-page", name: "自動化預約", cost: 1200, revenueChange: 420, costChange: 80, valueChange: 900, riskChange: -0.01, passiveChange: 0.08 },
      { id: "pet-helper", name: "聘請幫手", cost: 3200, revenueChange: 1900, costChange: 980, valueChange: 2200, riskChange: 0.02, passiveChange: 0.26 },
      { id: "premium-care", name: "增加服務", cost: 1800, revenueChange: 950, costChange: 220, valueChange: 1300, riskChange: 0.01, passiveChange: 0.02 },
    ],
  },
  {
    id: "used-book",
    name: "二手書店",
    category: "零售",
    description: "收購與販售二手童書和漫畫。",
    illustrationKey: "book-stack",
    startupCost: 9800,
    purchasePrice: 9800,
    monthlyRevenue: 5200,
    monthlyFixedCost: 1600,
    monthlyVariableCost: 1700,
    monthlyProfit: 1900,
    currentValue: 11800,
    resaleValue: 9800,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "普通",
    customerDemand: 1,
    staffCount: 1,
    ownerTimeRequired: 18,
    passiveRatio: 0.22,
    failureRisk: 0.09,
    eventSensitivity: 1,
    status: "available",
    childNote: "庫存需要花錢買，賣得慢時現金會被卡住。",
    upgradeOptions: [
      { id: "reading-corner", name: "擴大空間", cost: 4200, revenueChange: 1400, costChange: 500, valueChange: 3200, riskChange: 0.01, passiveChange: 0.03 },
      { id: "online-catalog", name: "自動化流程", cost: 3000, revenueChange: 1100, costChange: 220, valueChange: 2600, riskChange: -0.01, passiveChange: 0.12 },
      { id: "school-partner", name: "增加廣告", cost: 2600, revenueChange: 980, costChange: 180, valueChange: 1900, riskChange: 0, passiveChange: 0.01 },
    ],
  },
  {
    id: "handmade-card",
    name: "手作卡片店",
    category: "手作",
    description: "販售生日卡、節慶卡與客製插圖卡。",
    illustrationKey: "card-heart",
    startupCost: 3600,
    purchasePrice: 3600,
    monthlyRevenue: 2800,
    monthlyFixedCost: 420,
    monthlyVariableCost: 850,
    monthlyProfit: 1530,
    currentValue: 4500,
    resaleValue: 3700,
    riskLevel: "低",
    growthLevel: 1,
    maxLevel: 3,
    condition: "良好",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 16,
    passiveRatio: 0.12,
    failureRisk: 0.06,
    eventSensitivity: 0.9,
    status: "available",
    childNote: "手作商品有特色，但產量常被時間限制。",
    upgradeOptions: [
      { id: "print-tools", name: "改善設備", cost: 1800, revenueChange: 720, costChange: 120, valueChange: 1200, riskChange: -0.01, passiveChange: 0.05 },
      { id: "holiday-set", name: "增加服務", cost: 1400, revenueChange: 620, costChange: 160, valueChange: 900, riskChange: 0, passiveChange: 0.01 },
      { id: "online-shop", name: "自動化流程", cost: 2600, revenueChange: 980, costChange: 180, valueChange: 1800, riskChange: 0, passiveChange: 0.16 },
    ],
  },
  {
    id: "kids-code",
    name: "兒童程式課",
    category: "教育",
    description: "週末教孩子做簡單遊戲和動畫。",
    illustrationKey: "code-blocks",
    startupCost: 8200,
    purchasePrice: 8200,
    monthlyRevenue: 9000,
    monthlyFixedCost: 900,
    monthlyVariableCost: 1800,
    monthlyProfit: 6300,
    currentValue: 13000,
    resaleValue: 9000,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "良好",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 30,
    passiveRatio: 0.08,
    failureRisk: 0.1,
    eventSensitivity: 1.1,
    status: "available",
    childNote: "教學收入高，但需要你持續上課和準備教材。",
    upgradeOptions: [
      { id: "course-kit", name: "提升產品品質", cost: 3600, revenueChange: 1800, costChange: 280, valueChange: 2800, riskChange: -0.01, passiveChange: 0.04 },
      { id: "assistant-teacher", name: "聘請員工", cost: 6800, revenueChange: 5200, costChange: 2600, valueChange: 5600, riskChange: 0.02, passiveChange: 0.22 },
      { id: "recorded-class", name: "自動化流程", cost: 5200, revenueChange: 2400, costChange: 460, valueChange: 4200, riskChange: 0.01, passiveChange: 0.24 },
    ],
  },
  {
    id: "vending",
    name: "自動販賣機",
    category: "自動化",
    description: "在辦公樓放置飲料與小點心販賣機。",
    illustrationKey: "vending",
    startupCost: 18000,
    purchasePrice: 18000,
    monthlyRevenue: 7200,
    monthlyFixedCost: 900,
    monthlyVariableCost: 2700,
    monthlyProfit: 3600,
    currentValue: 21000,
    resaleValue: 18000,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "普通",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 6,
    passiveRatio: 0.72,
    failureRisk: 0.09,
    eventSensitivity: 1,
    status: "available",
    childNote: "機器能幫你賣東西，但補貨和維修仍要花錢。",
    upgradeOptions: [
      { id: "better-location", name: "增加廣告", cost: 4200, revenueChange: 1800, costChange: 240, valueChange: 3000, riskChange: 0.01, passiveChange: 0.02 },
      { id: "card-reader", name: "改善設備", cost: 3000, revenueChange: 1100, costChange: 120, valueChange: 2600, riskChange: -0.01, passiveChange: 0.06 },
      { id: "second-machine", name: "擴大空間", cost: 15000, revenueChange: 6200, costChange: 2600, valueChange: 15000, riskChange: 0.02, passiveChange: 0.04 },
    ],
  },
  {
    id: "laundry",
    name: "小型洗衣店",
    category: "自動化",
    description: "社區自助洗衣機和烘乾機。",
    illustrationKey: "laundry",
    startupCost: 42000,
    purchasePrice: 42000,
    monthlyRevenue: 18000,
    monthlyFixedCost: 5200,
    monthlyVariableCost: 4600,
    monthlyProfit: 8200,
    currentValue: 52000,
    resaleValue: 43000,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "普通",
    customerDemand: 1,
    staffCount: 1,
    ownerTimeRequired: 10,
    passiveRatio: 0.62,
    failureRisk: 0.1,
    eventSensitivity: 1,
    status: "available",
    childNote: "洗衣店較被動，但機器維修和租金很重要。",
    upgradeOptions: [
      { id: "efficient-machines", name: "改善設備", cost: 12000, revenueChange: 3600, costChange: -900, valueChange: 10000, riskChange: -0.02, passiveChange: 0.06 },
      { id: "wash-fold", name: "增加服務", cost: 8000, revenueChange: 5200, costChange: 2400, valueChange: 6000, riskChange: 0.02, passiveChange: -0.08 },
      { id: "auto-payment", name: "自動化流程", cost: 6500, revenueChange: 1600, costChange: -400, valueChange: 5200, riskChange: -0.01, passiveChange: 0.12 },
    ],
  },
  {
    id: "illustration-shop",
    name: "網路插畫商店",
    category: "線上服務",
    description: "販售貼圖、模板和簡單客製插畫。",
    illustrationKey: "digital-pen",
    startupCost: 6200,
    purchasePrice: 6200,
    monthlyRevenue: 4800,
    monthlyFixedCost: 520,
    monthlyVariableCost: 980,
    monthlyProfit: 3300,
    currentValue: 8800,
    resaleValue: 6500,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "良好",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 18,
    passiveRatio: 0.32,
    failureRisk: 0.09,
    eventSensitivity: 1.1,
    status: "available",
    childNote: "線上商品可以重複賣，但需要持續更新作品。",
    upgradeOptions: [
      { id: "template-pack", name: "增加服務", cost: 2600, revenueChange: 1300, costChange: 140, valueChange: 2200, riskChange: 0, passiveChange: 0.08 },
      { id: "shop-automation", name: "自動化流程", cost: 3400, revenueChange: 900, costChange: -120, valueChange: 2600, riskChange: -0.01, passiveChange: 0.18 },
      { id: "ad-campaign", name: "增加廣告", cost: 2400, revenueChange: 1200, costChange: 220, valueChange: 1600, riskChange: 0.01, passiveChange: 0.01 },
    ],
  },
  {
    id: "home-bakery",
    name: "家庭烘焙坊",
    category: "食品",
    description: "週末接蛋糕和餅乾訂單。",
    illustrationKey: "bakery",
    startupCost: 7600,
    purchasePrice: 7600,
    monthlyRevenue: 6200,
    monthlyFixedCost: 800,
    monthlyVariableCost: 2300,
    monthlyProfit: 3100,
    currentValue: 9800,
    resaleValue: 7900,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "良好",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 24,
    passiveRatio: 0.08,
    failureRisk: 0.09,
    eventSensitivity: 1,
    status: "available",
    childNote: "烘焙坊受歡迎時很忙，但原料和時間成本也高。",
    upgradeOptions: [
      { id: "oven", name: "改善設備", cost: 4200, revenueChange: 1800, costChange: 240, valueChange: 3200, riskChange: -0.01, passiveChange: 0.02 },
      { id: "holiday-box", name: "提升產品品質", cost: 2400, revenueChange: 1300, costChange: 360, valueChange: 1700, riskChange: 0.01, passiveChange: 0 },
      { id: "delivery-helper", name: "聘請員工", cost: 5200, revenueChange: 2800, costChange: 1300, valueChange: 3600, riskChange: 0.01, passiveChange: 0.12 },
    ],
  },
  {
    id: "bike-repair",
    name: "社區腳踏車維修",
    category: "維修服務",
    description: "幫鄰居修輪胎、調煞車和保養腳踏車。",
    illustrationKey: "bike-wrench",
    startupCost: 5400,
    purchasePrice: 5400,
    monthlyRevenue: 5200,
    monthlyFixedCost: 620,
    monthlyVariableCost: 1100,
    monthlyProfit: 3480,
    currentValue: 7600,
    resaleValue: 5600,
    riskLevel: "中",
    growthLevel: 1,
    maxLevel: 3,
    condition: "普通",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 20,
    passiveRatio: 0.1,
    failureRisk: 0.08,
    eventSensitivity: 1,
    status: "available",
    childNote: "維修服務靠技能賺錢，也會受季節和天氣影響。",
    upgradeOptions: [
      { id: "tool-wall", name: "改善設備", cost: 2600, revenueChange: 1100, costChange: 120, valueChange: 2100, riskChange: -0.01, passiveChange: 0.02 },
      { id: "mobile-service", name: "增加服務", cost: 3200, revenueChange: 1700, costChange: 420, valueChange: 2400, riskChange: 0.01, passiveChange: -0.02 },
      { id: "repair-apprentice", name: "聘請員工", cost: 5800, revenueChange: 3100, costChange: 1500, valueChange: 4200, riskChange: 0.02, passiveChange: 0.18 },
    ],
  },
  {
    id: "cloud-tool",
    name: "小型雲端工具服務",
    category: "線上服務",
    description: "提供簡單班級報名和收款工具。",
    illustrationKey: "cloud-tool",
    startupCost: 24000,
    purchasePrice: 24000,
    monthlyRevenue: 9800,
    monthlyFixedCost: 1800,
    monthlyVariableCost: 1200,
    monthlyProfit: 6800,
    currentValue: 34000,
    resaleValue: 25000,
    riskLevel: "高",
    growthLevel: 1,
    maxLevel: 3,
    condition: "良好",
    customerDemand: 1,
    staffCount: 0,
    ownerTimeRequired: 12,
    passiveRatio: 0.55,
    failureRisk: 0.13,
    eventSensitivity: 1.2,
    status: "available",
    childNote: "雲端工具可重複服務很多人，但需要維護和更新。",
    upgradeOptions: [
      { id: "auto-billing", name: "自動化流程", cost: 7200, revenueChange: 2600, costChange: -300, valueChange: 6800, riskChange: -0.01, passiveChange: 0.12 },
      { id: "new-module", name: "增加服務", cost: 8600, revenueChange: 4200, costChange: 900, valueChange: 7600, riskChange: 0.02, passiveChange: 0.02 },
      { id: "support-helper", name: "聘請員工", cost: 9800, revenueChange: 3900, costChange: 2400, valueChange: 6200, riskChange: -0.01, passiveChange: 0.16 },
    ],
  },
];

export const businessRiskEvents = [
  { id: "more-customers", title: "顧客增加", kind: "demand", factor: 1.12, duration: 2, positive: true, text: "更多人知道你的生意，需求提高。" },
  { id: "good-review", title: "好評推薦", kind: "demand", factor: 1.08, duration: 3, positive: true, text: "顧客留下好評，帶來新訂單。" },
  { id: "school-orders", title: "學校活動帶來訂單", kind: "revenue", factor: 1.18, duration: 1, positive: true, text: "學校活動讓本月訂單增加。" },
  { id: "popular-product", title: "新產品受歡迎", kind: "revenue", factor: 1.12, duration: 2, positive: true, text: "新產品讓收入提高。" },
  { id: "cost-down", title: "成本下降", kind: "cost", factor: 0.9, duration: 2, positive: true, text: "找到更好的供應方式，成本下降。" },
  { id: "staff-efficiency", title: "員工效率提升", kind: "passive", passiveChange: 0.08, duration: 2, positive: true, text: "流程變順，花的時間減少。" },
  { id: "equipment-break", title: "設備損壞", kind: "oneTimeCost", costRate: 0.08, minCost: 800, duration: 1, positive: false, text: "設備損壞，需要維修。" },
  { id: "material-up", title: "原料上漲", kind: "cost", factor: 1.14, duration: 2, positive: false, text: "原料變貴，每月成本提高。" },
  { id: "less-customers", title: "顧客減少", kind: "demand", factor: 0.88, duration: 2, positive: false, text: "顧客變少，需求下降。" },
  { id: "staff-away", title: "員工請假", kind: "revenue", factor: 0.9, duration: 1, positive: false, text: "人手不足，本月收入下降。" },
  { id: "competition", title: "競爭增加", kind: "demand", factor: 0.9, duration: 3, positive: false, text: "附近出現類似生意，需求被分散。" },
  { id: "temporary-close", title: "臨時停業", kind: "revenue", factor: 0.72, duration: 1, positive: false, text: "臨時停業幾天，本月營收下降。" },
];

export const businessMarketEvents = [
  { id: "community-flow", title: "社區活動增加人流", categories: ["食品", "零售", "手作"], factor: 1.12, text: "社區活動帶來更多人流。" },
  { id: "school-start", title: "學期開始", categories: ["教育", "零售", "食品"], factor: 1.1, text: "學期開始，學習和校園消費增加。" },
  { id: "cool-economy", title: "經濟降溫", categories: ["零售", "手作", "娛樂", "食品"], factor: 0.92, text: "大家花錢更謹慎。" },
  { id: "online-up", title: "線上需求提升", categories: ["線上服務", "教育"], factor: 1.14, text: "更多人使用線上服務。" },
  { id: "supply-short", title: "原料短缺", categories: ["食品", "手作"], factor: 0.9, costFactor: 1.08, text: "原料短缺，需求和成本都受到影響。" },
  { id: "new-competitor", title: "競爭者加入", categories: ["食品", "寵物服務", "維修服務", "線上服務"], factor: 0.9, text: "新的競爭者加入市場。" },
  { id: "holiday-spend", title: "節慶消費增加", categories: ["食品", "手作", "零售"], factor: 1.16, text: "節慶讓消費增加。" },
  { id: "weather-impact", title: "天氣影響客流", categories: ["食品", "寵物服務", "維修服務"], factor: 0.93, text: "天氣讓出門客流減少。" },
];

export const businessLearningNotes = {
  revenue: "營收是收到的全部金額，但還沒扣除成本。",
  profit: "淨利是營收扣除所有成本後真正留下的錢。",
  fixedCost: "不管生意好不好，每月都要支付的費用叫固定成本。",
  variableCost: "賣得越多，可能跟著增加的成本叫變動成本。",
  upgrade: "升級可能增加收入，也可能帶來更多支出。",
  passive: "系統建立後，不需要一直工作也能產生的收入，較接近被動收入。",
};
