export const insurancePolicies = [
  {
    id: "basic-medical",
    name: "基础医疗保险",
    category: "medical",
    monthlyPremium: 260,
    deductible: 500,
    coverageRate: 0.55,
    coverageLimit: 8000,
    coveredEvents: ["medical"],
    waitingPeriod: 0,
    childNote: "保费是平常固定的小支出，用来减少某些大意外一次带来的压力。",
  },
  {
    id: "advanced-medical",
    name: "进阶医疗保险",
    category: "medical",
    monthlyPremium: 620,
    deductible: 300,
    coverageRate: 0.8,
    coverageLimit: 22000,
    coveredEvents: ["medical"],
    waitingPeriod: 1,
    childNote: "保障较高，保费也较高，要看每月现金流是否承受得住。",
  },
  {
    id: "auto-protection",
    name: "汽车保险",
    category: "accident",
    monthlyPremium: 210,
    deductible: 700,
    coverageRate: 0.7,
    coverageLimit: 12000,
    coveredEvents: ["accident", "legal"],
    waitingPeriod: 0,
    childNote: "保险不能让意外消失，但可以降低一次大支出的压力。",
  },
  {
    id: "home-protection",
    name: "房屋保险",
    category: "property",
    monthlyPremium: 380,
    deductible: 900,
    coverageRate: 0.65,
    coverageLimit: 18000,
    coveredEvents: ["accident", "emergency"],
    waitingPeriod: 1,
    childNote: "房子也可能遇到风险，保费要算进每月支出。",
  },
  {
    id: "unemployment-cover",
    name: "失业保险",
    category: "unemployment",
    monthlyPremium: 330,
    deductible: 0,
    coverageRate: 0.32,
    coverageLimit: 12000,
    coveredEvents: ["unemployment"],
    waitingPeriod: 1,
    childNote: "收入中断时，补助可以争取时间，但不会完全取代工资。",
  },
  {
    id: "business-cover",
    name: "小生意保险",
    category: "business",
    monthlyPremium: 290,
    deductible: 600,
    coverageRate: 0.6,
    coverageLimit: 14000,
    coveredEvents: ["legal", "emergency", "accident"],
    waitingPeriod: 0,
    childNote: "小生意有收入，也可能遇到责任和维修风险。",
  },
  {
    id: "accident-bundle",
    name: "综合意外保险",
    category: "accident",
    monthlyPremium: 480,
    deductible: 400,
    coverageRate: 0.72,
    coverageLimit: 16000,
    coveredEvents: ["medical", "accident", "legal"],
    waitingPeriod: 0,
    childNote: "综合保障范围较广，但仍有自付额和理赔上限。",
  },
];
