const optionPay = (id, label, multiplier = 1, note = "支付并结算") => ({
  id,
  label,
  cashMultiplier: multiplier,
  learningNote: note,
});

export const lifeEvents = [
  {
    id: "clinic-visit",
    type: "medical",
    category: "医疗与健康",
    title: "一般看诊",
    subtitle: "身体不舒服需要看医生",
    description: "及时处理小问题，避免拖成更大的支出。",
    illustrationKey: "clinic",
    severity: "低",
    probability: 0.8,
    durationMonths: 0,
    cashImpact: 900,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "medical",
    learningTip: "保險不能讓意外消失，但可以幫助你減少一次付出太多錢的風險。",
    options: [optionPay("full-care", "立即完整治疗", 1), optionPay("basic-care", "基础处理", 0.72, "费用较低，但仍要关注健康。")],
    resultRules: { kind: "claimableCost" },
    cooldown: 1,
    status: "active",
  },
  {
    id: "dental-care",
    type: "medical",
    category: "医疗与健康",
    title: "牙齿治疗",
    subtitle: "补牙和清洁一起做",
    description: "牙齿问题常常越拖越贵。",
    illustrationKey: "dental",
    severity: "中",
    probability: 0.45,
    durationMonths: 0,
    cashImpact: 3200,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "medical",
    learningTip: "小的健康支出也要放进预算里。",
    options: [optionPay("full-care", "完整治疗", 1), optionPay("staged-care", "分阶段处理", 0.78)],
    resultRules: { kind: "claimableCost" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "sports-injury",
    type: "medical",
    category: "医疗与健康",
    title: "运动受伤",
    subtitle: "需要检查和护具",
    description: "运动很棒，但意外也需要准备金。",
    illustrationKey: "sports-injury",
    severity: "中",
    probability: 0.35,
    durationMonths: 1,
    cashImpact: 4600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 500,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "medical",
    learningTip: "一次事件可能带来后续几个月的复健费用。",
    options: [optionPay("full-care", "立即完整处理", 1), optionPay("basic-care", "基础处理", 0.82)],
    resultRules: { kind: "claimableCost" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "vision-check",
    type: "medical",
    category: "医疗与健康",
    title: "视力检查",
    subtitle: "更换镜片",
    description: "学习和工作都需要好好照顾眼睛。",
    illustrationKey: "vision",
    severity: "低",
    probability: 0.4,
    durationMonths: 0,
    cashImpact: 1600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "medical",
    learningTip: "预防和检查也是财务计划的一部分。",
    options: [optionPay("standard", "标准镜片", 1), optionPay("budget", "经济方案", 0.7)],
    resultRules: { kind: "claimableCost" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "emergency-care",
    type: "medical",
    category: "医疗与健康",
    title: "紧急医疗",
    subtitle: "突发状况需要马上处理",
    description: "紧急事件通常不能慢慢等。",
    illustrationKey: "emergency-care",
    severity: "高",
    probability: 0.18,
    durationMonths: 2,
    cashImpact: 18000,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 900,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "medical",
    learningTip: "保险和预备金解决的是冲击，不是让风险消失。",
    options: [optionPay("full-care", "立即完整治疗", 1), optionPay("payment-plan", "基础处理", 0.88)],
    resultRules: { kind: "claimableCost" },
    cooldown: 6,
    status: "active",
  },
  {
    id: "rehab-cost",
    type: "medical",
    category: "医疗与健康",
    title: "复健支出",
    subtitle: "连续复健数月",
    description: "恢复健康需要时间和持续费用。",
    illustrationKey: "rehab",
    severity: "中",
    probability: 0.22,
    durationMonths: 3,
    cashImpact: 2200,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 1100,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "medical",
    learningTip: "持续费用会影响每月现金流。",
    options: [optionPay("regular", "规律复健", 1), optionPay("home-plan", "居家辅助方案", 0.65)],
    resultRules: { kind: "claimableCost" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "health-check",
    type: "medical",
    category: "医疗与健康",
    title: "健康检查",
    subtitle: "年度检查",
    description: "提早知道身体状况，有时能避免更大问题。",
    illustrationKey: "checkup",
    severity: "低",
    probability: 0.5,
    durationMonths: 0,
    cashImpact: 1300,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "medical",
    learningTip: "健康计划也可以提前预算。",
    options: [optionPay("standard", "标准检查", 1), optionPay("basic", "基础检查", 0.58)],
    resultRules: { kind: "claimableCost" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "family-medical",
    type: "medical",
    category: "医疗与健康",
    title: "家庭成员医疗",
    subtitle: "家人需要你的帮助",
    description: "家庭互相照顾很重要，也需要财务准备。",
    illustrationKey: "family-medical",
    severity: "中",
    probability: 0.28,
    durationMonths: 1,
    cashImpact: 7600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 600,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "medical",
    learningTip: "家庭责任不是错误选择，但需要预算。",
    options: [optionPay("support", "完整支持", 1), optionPay("shared", "与家人分担", 0.68)],
    resultRules: { kind: "claimableCost" },
    cooldown: 5,
    status: "active",
  },
  {
    id: "bike-accident",
    type: "accident",
    category: "意外与维修",
    title: "脚踏车意外维修",
    subtitle: "交通工具需要修理",
    description: "小意外也会带来现金支出。",
    illustrationKey: "bike",
    severity: "低",
    probability: 0.45,
    durationMonths: 0,
    cashImpact: 1800,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "accident",
    learningTip: "意外支出适合用预备金处理。",
    options: [optionPay("repair", "立即维修", 1), optionPay("simple", "基础维修", 0.62)],
    resultRules: { kind: "claimableCost" },
    cooldown: 2,
    status: "active",
  },
  {
    id: "phone-accident",
    type: "accident",
    category: "意外与维修",
    title: "手机进水",
    subtitle: "资料备份和维修",
    description: "没有预备金时，小物品维修也会让现金紧张。",
    illustrationKey: "phone-water",
    severity: "低",
    probability: 0.36,
    durationMonths: 0,
    cashImpact: 2600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "emergency",
    learningTip: "预备金和保险不同，有些小事只能靠现金。",
    options: [optionPay("repair", "维修", 1), optionPay("delay", "延后换新", 0.45)],
    resultRules: { kind: "directCost" },
    cooldown: 2,
    status: "active",
  },
  {
    id: "home-leak",
    type: "accident",
    category: "意外与维修",
    title: "家中漏水",
    subtitle: "需要找师傅处理",
    description: "居住环境也可能发生临时维修。",
    illustrationKey: "home-leak",
    severity: "中",
    probability: 0.24,
    durationMonths: 0,
    cashImpact: 5200,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "emergency",
    learningTip: "有些保单会帮忙分担，但仍可能有自付额。",
    options: [optionPay("repair", "完整维修", 1), optionPay("basic", "先止水", 0.7)],
    resultRules: { kind: "claimableCost" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "computer-repair",
    type: "accident",
    category: "意外与维修",
    title: "电脑维修",
    subtitle: "工作设备故障",
    description: "工具损坏可能影响工作效率。",
    illustrationKey: "computer",
    severity: "中",
    probability: 0.3,
    durationMonths: 0,
    cashImpact: 4300,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "emergency",
    learningTip: "重要工具也需要维修预算。",
    options: [optionPay("repair", "维修设备", 1), optionPay("borrow", "借用设备", 0.35)],
    resultRules: { kind: "directCost" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "moving-damage",
    type: "accident",
    category: "意外与维修",
    title: "搬家物品损坏",
    subtitle: "需要补买用品",
    description: "搬家除了车费，也可能有损耗。",
    illustrationKey: "moving-damage",
    severity: "低",
    probability: 0.22,
    durationMonths: 0,
    cashImpact: 2400,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "accident",
    learningTip: "选择不同方案，会改变支出和便利。",
    options: [optionPay("replace", "立即补齐", 1), optionPay("basic", "先买必需品", 0.55)],
    resultRules: { kind: "claimableCost" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "appliance-repair",
    type: "accident",
    category: "意外与维修",
    title: "家电维修",
    subtitle: "冰箱需要维修",
    description: "耐用品也会老化。",
    illustrationKey: "appliance",
    severity: "中",
    probability: 0.26,
    durationMonths: 0,
    cashImpact: 3600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "emergency",
    learningTip: "紧急预备金可以减少临时借款。",
    options: [optionPay("repair", "维修", 1), optionPay("used", "二手替换", 0.64)],
    resultRules: { kind: "claimableCost" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "layoff",
    type: "unemployment",
    category: "失业与工作",
    title: "公司裁员",
    subtitle: "工资暂时中断",
    description: "景气和公司状况会影响工作稳定。",
    illustrationKey: "layoff",
    severity: "高",
    probability: 0.2,
    durationMonths: 3,
    cashImpact: 0,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "unemployment",
    learningTip: "收入中断时，紧急预备金和较低固定支出会给你更多时间选择。",
    options: [{ id: "job-search", label: "开始找工作", learningNote: "每回合找工作会增加进度。" }],
    resultRules: { kind: "startUnemployment", months: 3 },
    cooldown: 8,
    status: "active",
  },
  {
    id: "contract-ended",
    type: "unemployment",
    category: "失业与工作",
    title: "合约结束",
    subtitle: "需要寻找下一份工作",
    description: "合约工作收入可能不错，但稳定性较低。",
    illustrationKey: "contract-end",
    severity: "中",
    probability: 0.18,
    durationMonths: 2,
    cashImpact: 0,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "unemployment",
    learningTip: "收入形式不同，风险也不同。",
    options: [{ id: "job-search", label: "寻找新合约", learningNote: "持续行动会提高机会。" }],
    resultRules: { kind: "startUnemployment", months: 2 },
    cooldown: 7,
    status: "active",
  },
  {
    id: "department-cut",
    type: "unemployment",
    category: "失业与工作",
    title: "部门缩编",
    subtitle: "职位被取消",
    description: "不是每次工作变化都来自个人表现。",
    illustrationKey: "department-cut",
    severity: "高",
    probability: 0.16,
    durationMonths: 3,
    cashImpact: 0,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "unemployment",
    learningTip: "固定支出越低，遇到变化时越有弹性。",
    options: [{ id: "job-search", label: "整理履历", learningNote: "准备越好，重新就业越快。" }],
    resultRules: { kind: "startUnemployment", months: 3 },
    cooldown: 9,
    status: "active",
  },
  {
    id: "performance-plan",
    type: "unemployment",
    category: "失业与工作",
    title: "表现改善计划",
    subtitle: "需要补强技能",
    description: "选择进修或调整工作方式，都有成本和机会。",
    illustrationKey: "performance",
    severity: "中",
    probability: 0.22,
    durationMonths: 2,
    cashImpact: 2600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "education",
    learningTip: "进修不是保证加薪，但能提高未来机会。",
    options: [optionPay("course", "支付课程", 1, "提升技能和稳定性。"), optionPay("self-study", "自学方案", 0.3)],
    resultRules: { kind: "skill", skillChange: 1, stressChange: 1 },
    cooldown: 5,
    status: "active",
  },
  {
    id: "job-opportunity",
    type: "unemployment",
    category: "失业与工作",
    title: "新工作机会",
    subtitle: "收到面试邀请",
    description: "准备面试需要时间，也可能带来更好的薪资。",
    illustrationKey: "job-opportunity",
    severity: "低",
    probability: 0.42,
    durationMonths: 0,
    cashImpact: 800,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "education",
    learningTip: "机会也需要准备成本。",
    options: [optionPay("prepare", "认真准备", 1), optionPay("basic", "简单准备", 0.35)],
    resultRules: { kind: "jobSearch", progress: 35 },
    cooldown: 3,
    status: "active",
  },
  {
    id: "interview-success",
    type: "unemployment",
    category: "失业与工作",
    title: "面试成功",
    subtitle: "恢复就业",
    description: "重新就业后，工资恢复并可能调整。",
    illustrationKey: "interview",
    severity: "正面",
    probability: 0.36,
    durationMonths: 0,
    cashImpact: 0,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "unemployment",
    learningTip: "重新就业会恢复工资，但新工资可能高或低。",
    options: [{ id: "accept", label: "接受工作", salaryMultiplier: 1 }],
    resultRules: { kind: "reemploy", salaryMultiplier: 1 },
    cooldown: 2,
    status: "active",
  },
  {
    id: "career-raise-switch",
    type: "unemployment",
    category: "失业与工作",
    title: "转职加薪",
    subtitle: "新岗位薪资更好",
    description: "转换职涯可能带来收入成长，也需要适应。",
    illustrationKey: "career-up",
    severity: "正面",
    probability: 0.22,
    durationMonths: 0,
    cashImpact: 1200,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 700,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "education",
    learningTip: "升职加薪也可能增加通勤、服装或学习支出。",
    options: [optionPay("accept", "接受新职涯", 1)],
    resultRules: { kind: "salaryMultiplier", multiplier: 1.12 },
    cooldown: 6,
    status: "active",
  },
  {
    id: "career-pay-cut",
    type: "unemployment",
    category: "失业与工作",
    title: "转职减薪",
    subtitle: "先换到稳定工作",
    description: "有时先恢复收入，比等待完美工作更重要。",
    illustrationKey: "career-down",
    severity: "中",
    probability: 0.2,
    durationMonths: 0,
    cashImpact: 0,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: -300,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "unemployment",
    learningTip: "短期选择和长期发展可以分开考虑。",
    options: [{ id: "accept", label: "接受稳定工作", salaryMultiplier: 0.9 }],
    resultRules: { kind: "reemploy", salaryMultiplier: 0.9 },
    cooldown: 5,
    status: "active",
  },
  {
    id: "family-move",
    type: "family",
    category: "家庭责任",
    title: "搬家",
    subtitle: "换到更合适的住处",
    description: "搬家不是好坏问题，而是生活需求和现金流选择。",
    illustrationKey: "move",
    severity: "中",
    probability: 0.25,
    durationMonths: 0,
    cashImpact: 6800,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 800,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "family",
    learningTip: "家庭责任不是负面选择，但要看现金和月支出。",
    options: [optionPay("basic", "基本方案", 0.78), optionPay("comfort", "较舒适方案", 1.18), optionPay("delay", "延后", 0.18)],
    resultRules: { kind: "ongoingExpense" },
    cooldown: 7,
    status: "active",
  },
  {
    id: "family-trip",
    type: "family",
    category: "家庭责任",
    title: "家庭旅游",
    subtitle: "安排共同回忆",
    description: "快乐和关系也有价值，只是要放进预算。",
    illustrationKey: "family-trip",
    severity: "低",
    probability: 0.32,
    durationMonths: 0,
    cashImpact: 8200,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "family",
    learningTip: "预算不是禁止快乐，而是先知道会花多少钱。",
    options: [optionPay("basic", "基本方案", 0.65), optionPay("comfort", "较舒适方案", 1.15), optionPay("delay", "延后", 0.1)],
    resultRules: { kind: "directCost" },
    cooldown: 5,
    status: "active",
  },
  {
    id: "child-education",
    type: "family",
    category: "家庭责任",
    title: "小孩教育支出",
    subtitle: "课程和学习材料",
    description: "教育支出可以是投资，也需要现金计划。",
    illustrationKey: "child-education",
    severity: "中",
    probability: 0.3,
    durationMonths: 4,
    cashImpact: 2400,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 1500,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "family",
    learningTip: "持续支出要看每月现金流。",
    options: [optionPay("basic", "基本方案", 0.75), optionPay("comfort", "较舒适方案", 1.2), optionPay("delay", "延后部分课程", 0.35)],
    resultRules: { kind: "ongoingExpense" },
    cooldown: 5,
    status: "active",
  },
  {
    id: "care-family",
    type: "family",
    category: "家庭责任",
    title: "照顾家人",
    subtitle: "安排陪伴与照护",
    description: "照顾家人是责任，也会影响时间和支出。",
    illustrationKey: "care-family",
    severity: "中",
    probability: 0.24,
    durationMonths: 3,
    cashImpact: 3000,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 1200,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "family",
    learningTip: "有些选择不能只看钱，也要看家庭需要。",
    options: [optionPay("basic", "基本照护", 0.82), optionPay("support", "增加协助", 1.25)],
    resultRules: { kind: "ongoingExpense" },
    cooldown: 6,
    status: "active",
  },
  {
    id: "pet-cost",
    type: "family",
    category: "家庭责任",
    title: "宠物支出",
    subtitle: "检查和用品",
    description: "照顾宠物也要预算。",
    illustrationKey: "pet",
    severity: "低",
    probability: 0.34,
    durationMonths: 2,
    cashImpact: 1800,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 350,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "family",
    learningTip: "固定小支出累积起来也会影响现金流。",
    options: [optionPay("basic", "基本方案", 0.8), optionPay("comfort", "较舒适方案", 1.15)],
    resultRules: { kind: "ongoingExpense" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "family-celebration",
    type: "family",
    category: "家庭责任",
    title: "家庭庆祝活动",
    subtitle: "重要日子到了",
    description: "庆祝可以简单，也可以隆重。",
    illustrationKey: "celebration",
    severity: "低",
    probability: 0.38,
    durationMonths: 0,
    cashImpact: 3600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "family",
    learningTip: "不同方案都有取舍，没有永远正确的答案。",
    options: [optionPay("basic", "基本方案", 0.55), optionPay("comfort", "较舒适方案", 1.1), optionPay("delay", "延后", 0.15)],
    resultRules: { kind: "directCost" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "tax-quarter",
    type: "tax",
    category: "税务",
    title: "季度税务预估",
    subtitle: "游戏中的简化税务规则",
    description: "收入增加时，也要记得可能有税务责任。",
    illustrationKey: "tax-quarter",
    severity: "中",
    probability: 0.3,
    durationMonths: 0,
    cashImpact: 0,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "tax",
    learningTip: "提前预留，可以避免到期时现金不足。",
    options: [{ id: "settle", label: "完成税务结算", learningNote: "这是游戏规则，不是真实报税建议。" }],
    resultRules: { kind: "taxSettlement" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "tax-underpaid",
    type: "tax",
    category: "税务",
    title: "税款预留不足",
    subtitle: "需要补缴",
    description: "没有提前准备，结算时现金压力会变大。",
    illustrationKey: "tax-underpaid",
    severity: "中",
    probability: 0.24,
    durationMonths: 0,
    cashImpact: 4200,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "tax",
    learningTip: "收入不是全部都能马上花掉。",
    options: [optionPay("pay", "补缴", 1), optionPay("partial", "先缴一部分", 0.55)],
    resultRules: { kind: "taxCost" },
    cooldown: 5,
    status: "active",
  },
  {
    id: "tax-refund",
    type: "tax",
    category: "税务",
    title: "税务退回",
    subtitle: "游戏规则下多预留了钱",
    description: "提前预留太多时，会在结算后拿回一部分。",
    illustrationKey: "tax-refund",
    severity: "正面",
    probability: 0.18,
    durationMonths: 0,
    cashImpact: -2600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "tax",
    learningTip: "预估是练习，不是真实税法。",
    options: [{ id: "receive", label: "收到退回" }],
    resultRules: { kind: "bonus" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "business-tax-fee",
    type: "tax",
    category: "税务",
    title: "小生意税务资料",
    subtitle: "整理收入和成本",
    description: "经营生意时，记录很重要。",
    illustrationKey: "business-tax",
    severity: "低",
    probability: 0.22,
    durationMonths: 0,
    cashImpact: 1800,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "tax",
    learningTip: "把收入和成本记清楚，比较容易做决定。",
    options: [optionPay("organize", "整理资料", 1), optionPay("simple", "简化整理", 0.55)],
    resultRules: { kind: "taxCost" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "tax-saving-plan",
    type: "tax",
    category: "税务",
    title: "税务预留计划",
    subtitle: "提前把一部分现金放一边",
    description: "游戏中的预留规则可降低结算压力。",
    illustrationKey: "tax-saving",
    severity: "低",
    probability: 0.2,
    durationMonths: 0,
    cashImpact: 3000,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "tax",
    learningTip: "预留税款不是消失，只是先准备好。",
    options: [optionPay("reserve", "预留税款", 1), optionPay("small", "少量预留", 0.45)],
    resultRules: { kind: "taxReserve" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "traffic-fine",
    type: "legal",
    category: "法律与罚款",
    title: "交通罚款",
    subtitle: "收到罚单",
    description: "这是简化游戏事件，不是法律建议。",
    illustrationKey: "traffic",
    severity: "低",
    probability: 0.26,
    durationMonths: 0,
    cashImpact: 1200,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "legal",
    learningTip: "责任支出也要用现金或预备金处理。",
    options: [optionPay("pay", "缴清", 1)],
    resultRules: { kind: "directCost" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "contract-dispute",
    type: "legal",
    category: "法律与罚款",
    title: "合约纠纷",
    subtitle: "需要咨询与协调",
    description: "游戏只做简化财务影响，不提供法律建议。",
    illustrationKey: "contract",
    severity: "中",
    probability: 0.16,
    durationMonths: 0,
    cashImpact: 6800,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "legal",
    learningTip: "签约前看清楚，可以减少未来麻烦。",
    options: [optionPay("settle", "协调处理", 1), optionPay("basic", "基础咨询", 0.62)],
    resultRules: { kind: "claimableCost" },
    cooldown: 6,
    status: "active",
  },
  {
    id: "license-renewal",
    type: "legal",
    category: "法律与罚款",
    title: "牌照续期",
    subtitle: "固定责任费用",
    description: "有些费用不是意外，而是定期责任。",
    illustrationKey: "license",
    severity: "低",
    probability: 0.28,
    durationMonths: 0,
    cashImpact: 1700,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "legal",
    learningTip: "定期费用最好提前放进预算。",
    options: [optionPay("renew", "续期", 1)],
    resultRules: { kind: "directCost" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "business-report-fee",
    type: "legal",
    category: "法律与罚款",
    title: "小生意申报费用",
    subtitle: "需要补交资料费",
    description: "经营活动也会有责任成本。",
    illustrationKey: "report",
    severity: "低",
    probability: 0.2,
    durationMonths: 0,
    cashImpact: 2400,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "legal",
    learningTip: "收入之外，也要记得合规成本。",
    options: [optionPay("file", "完成申报", 1), optionPay("simple", "简化服务", 0.7)],
    resultRules: { kind: "claimableCost" },
    cooldown: 5,
    status: "active",
  },
  {
    id: "property-rule-fee",
    type: "legal",
    category: "法律与罚款",
    title: "房屋管理违规",
    subtitle: "管理处要求整改",
    description: "持有资产也会伴随责任。",
    illustrationKey: "property-rule",
    severity: "中",
    probability: 0.14,
    durationMonths: 0,
    cashImpact: 3600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "legal",
    learningTip: "资产越多，管理责任也会增加。",
    options: [optionPay("fix", "整改", 1), optionPay("basic", "基础处理", 0.75)],
    resultRules: { kind: "directCost" },
    cooldown: 5,
    status: "active",
  },
  {
    id: "customer-refund",
    type: "legal",
    category: "法律与罚款",
    title: "消费退款责任",
    subtitle: "客户要求合理退款",
    description: "做生意要把服务责任也算进去。",
    illustrationKey: "refund",
    severity: "低",
    probability: 0.18,
    durationMonths: 0,
    cashImpact: 2100,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: true,
    insuranceCategory: "legal",
    learningTip: "收入高时也要留钱处理售后责任。",
    options: [optionPay("refund", "退款处理", 1), optionPay("coupon", "部分退款", 0.58)],
    resultRules: { kind: "claimableCost" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "performance-raise",
    type: "salaryRaise",
    category: "升职奖金与进修",
    title: "表现优良加薪",
    subtitle: "工资提高",
    description: "稳定成长也会改善现金流。",
    illustrationKey: "raise",
    severity: "正面",
    probability: 0.3,
    durationMonths: 0,
    cashImpact: 0,
    monthlyIncomeImpact: 1800,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "bonus",
    learningTip: "加薪要保存进未来月份，而不是只看一次现金。",
    options: [{ id: "accept", label: "接受加薪" }],
    resultRules: { kind: "salaryChange" },
    cooldown: 5,
    status: "active",
  },
  {
    id: "promotion",
    type: "promotion",
    category: "升职奖金与进修",
    title: "升职",
    subtitle: "收入提高但支出也增加",
    description: "职位提高可能带来通勤、服装或学习成本。",
    illustrationKey: "promotion",
    severity: "正面",
    probability: 0.22,
    durationMonths: 0,
    cashImpact: 0,
    monthlyIncomeImpact: 4200,
    monthlyExpenseImpact: 900,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "bonus",
    learningTip: "收入增加不代表现金流一定增加，要看新增支出。",
    options: [{ id: "accept", label: "接受升职" }],
    resultRules: { kind: "promotion", jobLevelChange: 1, stressChange: 1 },
    cooldown: 6,
    status: "active",
  },
  {
    id: "annual-bonus",
    type: "bonus",
    category: "升职奖金与进修",
    title: "年终奖金",
    subtitle: "收到一笔额外收入",
    description: "一次性收入适合分配到储蓄、投资和支出。",
    illustrationKey: "bonus",
    severity: "正面",
    probability: 0.28,
    durationMonths: 0,
    cashImpact: -12000,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "bonus",
    learningTip: "奖金是一次性，不要当成每月固定收入。",
    options: [{ id: "receive", label: "领取奖金" }],
    resultRules: { kind: "bonus" },
    cooldown: 6,
    status: "active",
  },
  {
    id: "certificate",
    type: "education",
    category: "升职奖金与进修",
    title: "完成证照",
    subtitle: "技能提升",
    description: "学习需要成本和时间，也可能提升未来机会。",
    illustrationKey: "certificate",
    severity: "正面",
    probability: 0.24,
    durationMonths: 0,
    cashImpact: 4200,
    monthlyIncomeImpact: 900,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "education",
    learningTip: "进修不能保证加薪，但能增加机会。",
    options: [optionPay("course", "完成课程", 1), optionPay("self-study", "自学考试", 0.45)],
    resultRules: { kind: "skillSalary" },
    cooldown: 5,
    status: "active",
  },
  {
    id: "study-success",
    type: "education",
    category: "升职奖金与进修",
    title: "进修成功",
    subtitle: "未来机会增加",
    description: "持续学习会提高技能等级。",
    illustrationKey: "study",
    severity: "正面",
    probability: 0.28,
    durationMonths: 0,
    cashImpact: 2800,
    monthlyIncomeImpact: 700,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "education",
    learningTip: "学习是提高选择权的一种方式。",
    options: [optionPay("class", "支付课程", 1), optionPay("library", "低成本学习", 0.22)],
    resultRules: { kind: "skillSalary" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "extra-task",
    type: "bonus",
    category: "升职奖金与进修",
    title: "接到额外任务",
    subtitle: "短期收入增加",
    description: "额外任务带来奖金，也可能提高压力。",
    illustrationKey: "extra-task",
    severity: "正面",
    probability: 0.34,
    durationMonths: 1,
    cashImpact: -3600,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 300,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "bonus",
    learningTip: "更多收入也可能伴随更多时间成本。",
    options: [{ id: "accept", label: "接受任务" }],
    resultRules: { kind: "bonus" },
    cooldown: 3,
    status: "active",
  },
  {
    id: "work-stress",
    type: "education",
    category: "升职奖金与进修",
    title: "工作压力增加",
    subtitle: "需要调整生活",
    description: "压力会带来额外支出，也提醒你平衡生活。",
    illustrationKey: "stress",
    severity: "中",
    probability: 0.3,
    durationMonths: 2,
    cashImpact: 1200,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 600,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "education",
    learningTip: "现金流之外，也要看时间和压力。",
    options: [optionPay("support", "安排支持", 1), optionPay("basic", "基础调整", 0.42)],
    resultRules: { kind: "stressExpense" },
    cooldown: 4,
    status: "active",
  },
  {
    id: "career-change",
    type: "promotion",
    category: "升职奖金与进修",
    title: "转换职涯",
    subtitle: "重新选择方向",
    description: "转换职涯不是保证变好，但可能带来新的成长路径。",
    illustrationKey: "career-change",
    severity: "中",
    probability: 0.18,
    durationMonths: 0,
    cashImpact: 5200,
    monthlyIncomeImpact: 1600,
    monthlyExpenseImpact: 500,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "education",
    learningTip: "重要选择通常同时有成本和机会。",
    options: [optionPay("switch", "转换职涯", 1), optionPay("prepare", "先准备", 0.45)],
    resultRules: { kind: "skillSalary" },
    cooldown: 7,
    status: "active",
  },
  {
    id: "emergency-fund-check",
    type: "emergency",
    category: "紧急预备金",
    title: "预备金检视",
    subtitle: "检查现金安全垫",
    description: "预备金和保险不同，一个是现金，一个是分担特定风险。",
    illustrationKey: "emergency-fund",
    severity: "教育",
    probability: 0.35,
    durationMonths: 0,
    cashImpact: 0,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "emergency",
    learningTip: "没有唯一正确月数，重点是知道自己能撑多久。",
    options: [{ id: "review", label: "查看预备金" }],
    resultRules: { kind: "emergencyReview" },
    cooldown: 2,
    status: "active",
  },
  {
    id: "economy-cycle-news",
    type: "economicCycle",
    category: "景气循环",
    title: "景气变化新闻",
    subtitle: "环境正在改变",
    description: "景气会影响工作、利率和市场，但不会决定一切。",
    illustrationKey: "economy",
    severity: "教育",
    probability: 0.3,
    durationMonths: 3,
    cashImpact: 0,
    monthlyIncomeImpact: 0,
    monthlyExpenseImpact: 0,
    assetImpact: 0,
    liabilityImpact: 0,
    insuranceEligible: false,
    insuranceCategory: "economy",
    learningTip: "同样的选择，在不同景气下风险感受会不一样。",
    options: [{ id: "update", label: "更新景气状态" }],
    resultRules: { kind: "economyCycle" },
    cooldown: 3,
    status: "active",
  },
];

export function getLifeEventById(eventId) {
  return lifeEvents.find((event) => event.id === eventId) || null;
}
