export const propertyCategories = [
  "小套房",
  "学生公寓",
  "双拼屋",
  "郊区住宅",
  "商店店面",
  "停车位",
  "小型仓库",
  "度假小屋",
  "小型办公空间",
  "多户住宅",
];

export const realEstateOpportunities = [
  {
    id: "studio-near-metro",
    name: "地铁旁小套房",
    category: "小套房",
    description: "面积不大，但通勤方便，适合刚工作的租客。",
    illustrationKey: "compact-home",
    purchasePrice: 220000,
    downPayment: 36000,
    mortgagePayment: 2850,
    monthlyRent: 5200,
    managementFee: 450,
    repairReserve: 550,
    riskLevel: "低",
    locationQuality: "A",
    condition: "良好",
    units: 1,
    appreciationRate: 0.003,
    childNote: "小房子也可以是资产，重点是租金扣掉贷款和维修后还剩多少。",
  },
  {
    id: "student-flat-4rooms",
    name: "四房学生公寓",
    category: "学生公寓",
    description: "靠近学校，按房间出租，现金流高但换租频繁。",
    illustrationKey: "student-flat",
    purchasePrice: 360000,
    downPayment: 58000,
    mortgagePayment: 4480,
    monthlyRent: 8800,
    managementFee: 900,
    repairReserve: 780,
    riskLevel: "中",
    locationQuality: "A",
    condition: "普通",
    units: 4,
    appreciationRate: 0.0025,
    childNote: "租给更多人，收入可能更高，也更需要管理和维修预算。",
  },
  {
    id: "duplex-family",
    name: "社区双拼屋",
    category: "双拼屋",
    description: "一边自住型租客，一边小家庭，租约稳定。",
    illustrationKey: "duplex",
    purchasePrice: 520000,
    downPayment: 82000,
    mortgagePayment: 6550,
    monthlyRent: 11200,
    managementFee: 1050,
    repairReserve: 950,
    riskLevel: "中",
    locationQuality: "B",
    condition: "良好",
    units: 2,
    appreciationRate: 0.0028,
    childNote: "双拼屋像两份租金一起工作，但贷款也更大。",
  },
  {
    id: "suburb-house",
    name: "郊区家庭住宅",
    category: "郊区住宅",
    description: "总价较高，租客稳定，升值取决于周边发展。",
    illustrationKey: "suburb-house",
    purchasePrice: 680000,
    downPayment: 118000,
    mortgagePayment: 8350,
    monthlyRent: 13200,
    managementFee: 1150,
    repairReserve: 1250,
    riskLevel: "中",
    locationQuality: "B",
    condition: "良好",
    units: 1,
    appreciationRate: 0.0022,
    childNote: "大房子看起来值钱，但每月是否赚钱要看现金流。",
  },
  {
    id: "street-shop",
    name: "社区商店店面",
    category: "商店店面",
    description: "街角小店面，租约较长，但空置后重新招租较慢。",
    illustrationKey: "shopfront",
    purchasePrice: 420000,
    downPayment: 76000,
    mortgagePayment: 5200,
    monthlyRent: 9800,
    managementFee: 800,
    repairReserve: 650,
    riskLevel: "中",
    locationQuality: "A",
    condition: "良好",
    units: 1,
    appreciationRate: 0.002,
    childNote: "商铺的租客常签较长合约，但地段很重要。",
  },
  {
    id: "parking-space",
    name: "医院旁停车位",
    category: "停车位",
    description: "维护简单，租金稳定，适合现金较少时练习。",
    illustrationKey: "parking",
    purchasePrice: 62000,
    downPayment: 18000,
    mortgagePayment: 820,
    monthlyRent: 1650,
    managementFee: 120,
    repairReserve: 80,
    riskLevel: "低",
    locationQuality: "A",
    condition: "良好",
    units: 1,
    appreciationRate: 0.0012,
    childNote: "停车位也是房地产，虽然小，但容易看懂收入和支出。",
  },
  {
    id: "mini-warehouse",
    name: "城郊小型仓库",
    category: "小型仓库",
    description: "给电商卖家存货，租金不错，维修集中在卷门和防水。",
    illustrationKey: "warehouse",
    purchasePrice: 280000,
    downPayment: 50000,
    mortgagePayment: 3350,
    monthlyRent: 6600,
    managementFee: 520,
    repairReserve: 520,
    riskLevel: "中",
    locationQuality: "B",
    condition: "普通",
    units: 1,
    appreciationRate: 0.0018,
    childNote: "仓库不漂亮，但能不能赚钱要看租金是否稳定。",
  },
  {
    id: "holiday-cabin",
    name: "湖边度假小屋",
    category: "度假小屋",
    description: "旺季收入高，淡季空置风险也高。",
    illustrationKey: "cabin",
    purchasePrice: 310000,
    downPayment: 62000,
    mortgagePayment: 3820,
    monthlyRent: 7200,
    managementFee: 950,
    repairReserve: 980,
    riskLevel: "高",
    locationQuality: "B",
    condition: "普通",
    units: 1,
    appreciationRate: 0.0024,
    childNote: "度假房有旺季和淡季，所以要准备更多安全现金。",
  },
  {
    id: "small-office",
    name: "小型办公空间",
    category: "小型办公空间",
    description: "适合工作室和咨询公司，租金中等，装修影响出租速度。",
    illustrationKey: "office",
    purchasePrice: 390000,
    downPayment: 72000,
    mortgagePayment: 4850,
    monthlyRent: 8900,
    managementFee: 880,
    repairReserve: 620,
    riskLevel: "中",
    locationQuality: "B",
    condition: "良好",
    units: 1,
    appreciationRate: 0.0019,
    childNote: "办公室要看租客生意稳不稳定，不只看租金数字。",
  },
  {
    id: "six-unit-house",
    name: "六户小公寓楼",
    category: "多户住宅",
    description: "六户分散风险，价格高，管理也更复杂。",
    illustrationKey: "multi-family",
    purchasePrice: 880000,
    downPayment: 160000,
    mortgagePayment: 10600,
    monthlyRent: 19800,
    managementFee: 1850,
    repairReserve: 1800,
    riskLevel: "高",
    locationQuality: "A",
    condition: "普通",
    units: 6,
    appreciationRate: 0.0026,
    childNote: "很多户能分散空置风险，但你也要更会管理钱。",
  },
  {
    id: "old-town-studio",
    name: "老城翻新小套房",
    category: "小套房",
    description: "价格低，维修多，翻新后租金有提升空间。",
    illustrationKey: "renovation-studio",
    purchasePrice: 180000,
    downPayment: 28000,
    mortgagePayment: 2350,
    monthlyRent: 4300,
    managementFee: 420,
    repairReserve: 760,
    riskLevel: "中",
    locationQuality: "B",
    condition: "待改善",
    units: 1,
    appreciationRate: 0.002,
    childNote: "便宜不一定安全，要把维修钱先算进去。",
  },
  {
    id: "station-parking-pack",
    name: "车站双停车位",
    category: "停车位",
    description: "两个连号车位，租客多为通勤族。",
    illustrationKey: "parking-pack",
    purchasePrice: 116000,
    downPayment: 30000,
    mortgagePayment: 1580,
    monthlyRent: 3200,
    managementFee: 220,
    repairReserve: 130,
    riskLevel: "低",
    locationQuality: "A",
    condition: "良好",
    units: 2,
    appreciationRate: 0.0013,
    childNote: "两个小资产加起来，也能慢慢提高被动收入。",
  },
];

export const realEstateMarketEvents = [
  { id: "value-up-small", title: "房市小幅上涨", kind: "value", factor: 1.04, text: "买家变多，你持有房产的市场价小幅提高。" },
  { id: "value-up-big", title: "房市明显上涨", kind: "value", factor: 1.09, text: "区域成交热络，房价明显上涨。" },
  { id: "cooling", title: "房市降温", kind: "value", factor: 0.97, text: "买家观望，估值略微回落。" },
  { id: "value-down", title: "房价下跌", kind: "value", factor: 0.91, text: "市场变冷，房产估值下降。" },
  { id: "rent-up", title: "租金上涨", kind: "rent", factor: 1.08, text: "租赁需求增加，月租金提高。" },
  { id: "rent-down", title: "租金下降", kind: "rent", factor: 0.94, text: "附近新增供应，租金需要调低才容易出租。" },
  { id: "expense-up", title: "维修成本增加", kind: "expense", factor: 1.12, text: "材料和人工变贵，维修准备金提高。" },
  { id: "location-up", title: "地段改善", kind: "location", valueFactor: 1.06, rentFactor: 1.04, text: "新交通和商圈规划改善了地段。" },
];

export const propertyHoldingEvents = [
  { id: "pipe-repair", title: "水管维修", kind: "repair", costRate: 0.012, minCost: 1800, text: "水管漏水，需要立刻维修。" },
  { id: "roof-repair", title: "屋顶维修", kind: "repair", costRate: 0.018, minCost: 3200, text: "屋顶渗水，拖延会造成更大损失。" },
  { id: "vacancy", title: "空置一个月", kind: "vacancy", text: "租客搬走，本月少收一个月租金。" },
  { id: "lease-renewal", title: "租客续约", kind: "rent", factor: 1.04, text: "好租客续约，你小幅调高租金。" },
  { id: "management-fee-up", title: "管理费上涨", kind: "expense", factor: 1.08, text: "物业和管理服务涨价，每月支出增加。" },
  { id: "small-renovation", title: "小型翻修提升价值", kind: "renovation", costRate: 0.01, valueFactor: 1.045, rentFactor: 1.035, text: "小翻修让房子更好出租，也提升估值。" },
];
