export const stockDefinitions = [
  {
    id: "star-tech",
    symbol: "STAR",
    name: "星星科技",
    category: "成长股",
    description: "制作儿童编程设备和小型学习硬件。",
    illustrationKey: "star-chip",
    currentPrice: 88,
    previousPrice: 84,
    basePrice: 82,
    priceHistory: [78, 80, 79, 83, 84, 88],
    dividendPerShare: 0,
    dividendFrequency: 0,
    volatility: 0.08,
    riskLevel: "高",
    trend: "成长",
    marketCapLevel: "中",
    sector: "科技",
    eventSensitivity: 1.2,
    minimumPurchase: 1,
    maximumPurchase: 120,
    status: "active",
    childNote: "科技公司可能成长很快，价格也可能变化很大。",
  },
  {
    id: "green-future",
    symbol: "GREEN",
    name: "绿能未来",
    category: "主题股",
    description: "制造校园太阳能板和社区储能设备。",
    illustrationKey: "green-panel",
    currentPrice: 64,
    previousPrice: 66,
    basePrice: 62,
    priceHistory: [60, 61, 65, 66, 66, 64],
    dividendPerShare: 0.2,
    dividendFrequency: 3,
    volatility: 0.07,
    riskLevel: "中",
    trend: "成长",
    marketCapLevel: "中",
    sector: "绿能",
    eventSensitivity: 1.1,
    minimumPurchase: 1,
    maximumPurchase: 160,
    status: "active",
    childNote: "绿能机会来自长期需求，但补助和成本会影响价格。",
  },
  {
    id: "happy-food",
    symbol: "FOOD",
    name: "快乐食品",
    category: "股息股",
    description: "经营健康零食、早餐麦片和校园餐点。",
    illustrationKey: "happy-bowl",
    currentPrice: 42,
    previousPrice: 41,
    basePrice: 40,
    priceHistory: [39, 40, 40, 41, 41, 42],
    dividendPerShare: 0.35,
    dividendFrequency: 2,
    volatility: 0.035,
    riskLevel: "低",
    trend: "稳定",
    marketCapLevel: "大",
    sector: "消费",
    eventSensitivity: 0.8,
    minimumPurchase: 1,
    maximumPurchase: 220,
    status: "active",
    childNote: "稳定食品公司变化较小，但原料涨价也会影响利润。",
  },
  {
    id: "city-transport",
    symbol: "MOVE",
    name: "城市运输",
    category: "周期股",
    description: "提供城市电动车队、校车调度和短途运输。",
    illustrationKey: "city-bus",
    currentPrice: 55,
    previousPrice: 53,
    basePrice: 52,
    priceHistory: [50, 51, 52, 54, 53, 55],
    dividendPerShare: 0.15,
    dividendFrequency: 3,
    volatility: 0.06,
    riskLevel: "中",
    trend: "循环",
    marketCapLevel: "中",
    sector: "运输",
    eventSensitivity: 1,
    minimumPurchase: 1,
    maximumPurchase: 180,
    status: "active",
    childNote: "运输公司会受油价、维修费和城市活动影响。",
  },
  {
    id: "cloud-learning",
    symbol: "LEARN",
    name: "云端学习",
    category: "成长股",
    description: "做线上课程平台和学校作业系统。",
    illustrationKey: "cloud-book",
    currentPrice: 73,
    previousPrice: 70,
    basePrice: 68,
    priceHistory: [66, 68, 69, 71, 70, 73],
    dividendPerShare: 0,
    dividendFrequency: 0,
    volatility: 0.075,
    riskLevel: "高",
    trend: "成长",
    marketCapLevel: "中",
    sector: "教育",
    eventSensitivity: 1.15,
    minimumPurchase: 1,
    maximumPurchase: 140,
    status: "active",
    childNote: "学习平台可能受欢迎，也可能因为竞争而降价。",
  },
  {
    id: "healthy-life",
    symbol: "LIFE",
    name: "健康生活",
    category: "防守股",
    description: "经营运动课程、健康餐和家庭检测服务。",
    illustrationKey: "healthy-heart",
    currentPrice: 50,
    previousPrice: 49,
    basePrice: 48,
    priceHistory: [47, 48, 48, 49, 49, 50],
    dividendPerShare: 0.25,
    dividendFrequency: 2,
    volatility: 0.04,
    riskLevel: "低",
    trend: "稳定",
    marketCapLevel: "大",
    sector: "健康",
    eventSensitivity: 0.85,
    minimumPurchase: 1,
    maximumPurchase: 200,
    status: "active",
    childNote: "健康需求通常比较稳定，但公司仍需要经营得好。",
  },
  {
    id: "safe-bank",
    symbol: "SAFE",
    name: "安心银行",
    category: "股息股",
    description: "服务社区储蓄、小额贷款和家庭账户。",
    illustrationKey: "safe-bank",
    currentPrice: 38,
    previousPrice: 38,
    basePrice: 37,
    priceHistory: [36, 37, 37, 38, 38, 38],
    dividendPerShare: 0.3,
    dividendFrequency: 2,
    volatility: 0.03,
    riskLevel: "低",
    trend: "稳定",
    marketCapLevel: "大",
    sector: "金融",
    eventSensitivity: 0.8,
    minimumPurchase: 1,
    maximumPurchase: 260,
    status: "active",
    childNote: "银行股可能有股息，但经济放慢时也会受影响。",
  },
  {
    id: "smart-robot",
    symbol: "BOT",
    name: "智慧机器人",
    category: "成长股",
    description: "制造仓库机器人和家庭小助手。",
    illustrationKey: "robot",
    currentPrice: 96,
    previousPrice: 91,
    basePrice: 90,
    priceHistory: [86, 87, 89, 92, 91, 96],
    dividendPerShare: 0,
    dividendFrequency: 0,
    volatility: 0.095,
    riskLevel: "高",
    trend: "成长",
    marketCapLevel: "小",
    sector: "科技",
    eventSensitivity: 1.3,
    minimumPurchase: 1,
    maximumPurchase: 100,
    status: "active",
    childNote: "机器人很有想象力，但新产品可能延迟或失败。",
  },
  {
    id: "blue-logistics",
    symbol: "BLUE",
    name: "蓝海物流",
    category: "周期股",
    description: "帮商店和工厂配送货物。",
    illustrationKey: "blue-box",
    currentPrice: 47,
    previousPrice: 48,
    basePrice: 46,
    priceHistory: [45, 46, 47, 49, 48, 47],
    dividendPerShare: 0.18,
    dividendFrequency: 3,
    volatility: 0.055,
    riskLevel: "中",
    trend: "循环",
    marketCapLevel: "中",
    sector: "运输",
    eventSensitivity: 1,
    minimumPurchase: 1,
    maximumPurchase: 190,
    status: "active",
    childNote: "物流需求跟经济活动有关，旺的时候忙，慢的时候收入也会降。",
  },
  {
    id: "sunny-fun",
    symbol: "FUN",
    name: "阳光娱乐",
    category: "成长股",
    description: "制作亲子游戏、动画和线下活动。",
    illustrationKey: "sun-stage",
    currentPrice: 31,
    previousPrice: 34,
    basePrice: 32,
    priceHistory: [32, 33, 35, 36, 34, 31],
    dividendPerShare: 0,
    dividendFrequency: 0,
    volatility: 0.09,
    riskLevel: "高",
    trend: "循环",
    marketCapLevel: "小",
    sector: "娱乐",
    eventSensitivity: 1.25,
    minimumPurchase: 1,
    maximumPurchase: 240,
    status: "active",
    childNote: "娱乐产品可能突然受欢迎，也可能热度很快下降。",
  },
  {
    id: "community-retail",
    symbol: "SHOP",
    name: "社区零售",
    category: "防守股",
    description: "经营社区超市、文具店和便利服务。",
    illustrationKey: "corner-shop",
    currentPrice: 29,
    previousPrice: 29,
    basePrice: 28,
    priceHistory: [27, 28, 28, 29, 29, 29],
    dividendPerShare: 0.22,
    dividendFrequency: 2,
    volatility: 0.035,
    riskLevel: "低",
    trend: "稳定",
    marketCapLevel: "中",
    sector: "零售",
    eventSensitivity: 0.85,
    minimumPurchase: 1,
    maximumPurchase: 280,
    status: "active",
    childNote: "社区零售比较贴近日常生活，但消费下降时也会受影响。",
  },
  {
    id: "steady-market-fund",
    symbol: "FUND",
    name: "稳健市场基金",
    category: "基金",
    description: "分散持有多种虚构公司，目标是降低单一公司影响。",
    illustrationKey: "basket",
    currentPrice: 25,
    previousPrice: 25,
    basePrice: 25,
    priceHistory: [24, 25, 25, 25, 25, 25],
    dividendPerShare: 0.12,
    dividendFrequency: 1,
    volatility: 0.02,
    riskLevel: "低",
    trend: "稳定",
    marketCapLevel: "基金",
    sector: "基金",
    eventSensitivity: 0.55,
    minimumPurchase: 1,
    maximumPurchase: 400,
    status: "active",
    childNote: "基金像一篮子选择，能分散一部分风险，但不是没有风险。",
  },
];

export const stockMarketEvents = [
  { id: "market-up-small", title: "市场小幅上涨", scope: "market", factor: 1.025, text: "大家对未来稍微更有信心，股票整体小幅上涨。" },
  { id: "market-up-big", title: "市场明显上涨", scope: "market", factor: 1.06, text: "市场情绪热络，许多股票明显上涨。" },
  { id: "market-cool", title: "市场降温", scope: "market", factor: 0.975, text: "投资人变谨慎，价格略微回落。" },
  { id: "market-down", title: "市场下跌", scope: "market", factor: 0.93, text: "市场担心未来收入，股票普遍下跌。" },
  { id: "consumer-up", title: "消费信心提升", scope: "sector", sector: "消费", factor: 1.05, text: "家庭更愿意消费，消费相关股票受益。" },
  { id: "slow-economy", title: "经济放缓", scope: "market", factor: 0.96, text: "经济活动变慢，许多公司预期变弱。" },
  { id: "tech-demand", title: "科技需求增加", scope: "sector", sector: "科技", factor: 1.07, text: "学校和企业采购更多科技产品。" },
  { id: "green-support", title: "绿能补助增加", scope: "sector", sector: "绿能", factor: 1.08, text: "绿能补助提高，相关公司更受关注。" },
  { id: "transport-cost", title: "运输成本上升", scope: "sector", sector: "运输", factor: 0.94, text: "运输成本变高，相关公司利润受压。" },
  { id: "food-cost", title: "食品原料上涨", scope: "sector", sector: "消费", factor: 0.95, text: "食品原料上涨，食品公司成本增加。" },
  { id: "health-growth", title: "健康产业成长", scope: "sector", sector: "健康", factor: 1.06, text: "更多家庭重视健康，健康产业成长。" },
  { id: "retail-down", title: "零售消费下降", scope: "sector", sector: "零售", factor: 0.94, text: "社区消费下降，零售公司销售放慢。" },
  { id: "new-product", title: "推出受欢迎的新产品", scope: "company", factor: 1.09, text: "一家公司推出新产品并受到欢迎。" },
  { id: "delay", title: "产品延迟", scope: "company", factor: 0.92, text: "一家公司产品延迟，市场降低期待。" },
  { id: "management", title: "管理改善", scope: "company", factor: 1.05, text: "管理团队改善流程，投资人更有信心。" },
  { id: "revenue-miss", title: "营收不如预期", scope: "company", factor: 0.9, text: "一家公司收入低于预期，股价下跌。" },
  { id: "large-order", title: "获得大型订单", scope: "company", factor: 1.08, text: "一家公司获得大型订单，未来收入可能增加。" },
  { id: "public-issue", title: "发生公关问题", scope: "company", factor: 0.91, text: "一家公司出现公关问题，信任受到影响。" },
];

export const stockLearningNotes = {
  buy: "买股票代表你拥有公司的一小部分，但价格会随着表现和市场改变。",
  averageCost: "不同价格买入后，平均成本能帮助你看出整体买入价格。",
  unrealized: "还没有卖出前，涨跌只是目前的变化，并不是最终结果。",
  dividend: "有些公司会把部分成果分给股东，这叫股息。",
  risk: "可能获得较高回报的选择，通常也可能出现较大变化。",
  diversification: "不要把所有资金都放在同一个地方，但分散也不能消除所有风险。",
};
